import type { Tables, TablesInsert, TablesUpdate } from "./db/database.types";

/**
 * Represents a user profile.
 * Directly maps to the `profiles` table.
 */
export type ProfileDto = Tables<"profiles">;

/**
 * Command for updating a user profile.
 * Contains a subset of updatable fields from the `profiles` table.
 */
export type UpdateProfileCommand = Pick<TablesUpdate<"profiles">, "username" | "avatar_url" | "notification_enabled">;

/**
 * Summary of a flashcard set for list views.
 * Excludes fields like `user_id`, `deleted_at`, and `source_text`.
 */
export type FlashcardSetSummaryDto = Pick<
  Tables<"flashcard_sets">,
  "id" | "name" | "description" | "created_at" | "updated_at"
>;

/**
 * Represents an individual flashcard.
 * Excludes metadata fields not relevant to the client.
 */
export type FlashcardDto = Pick<
  Tables<"flashcards">,
  "id" | "front" | "back" | "media_url" | "created_at" | "updated_at"
>;

/**
 * Detailed view of a flashcard set, including all its flashcards.
 */
export type FlashcardSetDetailDto = FlashcardSetSummaryDto & {
  flashcards: FlashcardDto[];
};

/**
 * Command for creating a new flashcard set manually.
 */
export type CreateFlashcardSetCommand = Pick<TablesInsert<"flashcard_sets">, "name" | "description">;

/**
 * Command for updating an existing flashcard set.
 */
export type UpdateFlashcardSetCommand = Pick<TablesUpdate<"flashcard_sets">, "name" | "description">;

/**
 * Command for manually creating a new flashcard within a set.
 */
export type CreateFlashcardCommand = Pick<TablesInsert<"flashcards">, "front" | "back" | "media_url">;

/**
 * Command for updating an existing flashcard.
 */
export type UpdateFlashcardCommand = Pick<TablesUpdate<"flashcards">, "front" | "back" | "media_url">;

/**
 * Represents a flashcard to be generated by AI, without database IDs.
 */
export type AiGeneratedFlashcard = Pick<Tables<"flashcards">, "front" | "back">;

/**
 * Command for generating flashcards from source text.
 */
export interface GenerateFlashcardsCommand {
  source_text: string;
  setName: string;
}

/**
 * DTO for the response of a flashcard generation request.
 * Contains a temporary set for user preview before saving.
 */
export interface GenerateFlashcardsResponseDto {
  temp_id: string;
  setName: string;
  source_text: string;
  flashcards: AiGeneratedFlashcard[];
}

/**
 * Command to accept and permanently save a set of AI-generated flashcards.
 * Corresponds to the data from `GenerateFlashcardsResponseDto`.
 */
export type AcceptFlashcardsCommand = GenerateFlashcardsResponseDto;

/**
 * Represents a flashcard due for a review session.
 * This is a composite type from `learning_schedules` and `flashcards` tables.
 */
export type LearningSessionFlashcardDto = Pick<Tables<"flashcards">, "id" | "front" | "back"> & {
  flashcard_id: Tables<"flashcards">["id"];
  next_review_date: Tables<"learning_schedules">["next_review_date"];
};

/**
 * Command for submitting a flashcard review.
 * `quality` is based on the SM-2 algorithm's response quality scale (0-5).
 */
export interface SubmitReviewCommand {
  flashcard_id: Tables<"flashcards">["id"];
  quality: number;
}

/**
 * Response DTO after submitting a flashcard review.
 * Contains the updated spaced repetition data.
 */
export type SubmitReviewResponseDto = Pick<
  Tables<"learning_schedules">,
  "flashcard_id" | "next_review_date" | "interval" | "repetitions" | "ease_factor"
>;

/**
 * Command for rating an AI-generated flashcard.
 * `rating` is `1` for a thumbs-up or `-1` for a thumbs-down.
 */
export type RateFlashcardCommand = Pick<TablesInsert<"flashcard_ratings">, "rating">;
